package:
  name: dgl
  version: "0.2"

source:
  git_rev: 0.2.x
  git_url: https://github.com/dmlc/dgl.git

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - cython
  run:
    - python
    - numpy
    - scipy
    - networkx

about:
  home: https://github.com/dmlc/dgl.git
  license_file: ../../LICENSE
